#-----------------------------------------------------------------------
#                        global parameters
#-----------------------------------------------------------------------
# Engine global parameters that fix for each changed environment
# Such as `cache_time`, `structure_schema`, `module_key`
global_utc_timezone: "Asia/Bangkok"
